photo_homepage:
    path:     /
    defaults: { _controller: PhotoBundle:Default:index }

photo_list:
    path:     /photo/list
    defaults: { _controller: PhotoBundle:Photo:showPhoto}
photos_article:
    path:     /photo/list/{id}
    defaults: { _controller: PhotoBundle:Photo:showPhotos }
new_photo:
    path:     /user/newphoto
    defaults: { _controller: PhotoBundle:Photo:newPhoto }
