article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#routes persos
#partie publique

accueil:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

articlespublics_show:
    path:     /articles
    defaults: { _controller: ArticleBundle:Article:articlespublicsShow }

presentation:
    path:     /presentation
    defaults: { _controller: AppBundle:Presentation:presentation }

conseil:
    path:     /conseil
    defaults: { _controller: AppBundle:Conseil:conseilShow }

conseil_send:
    path:     /conseil_check
    defaults: { _controller: AppBundle:Conseil:conseilSend }

#partie privée

article_show:
    path:     /user/articles
    defaults: { _controller: ArticleBundle:Article:articleShow }

article_create:
    path:     /article/new
    defaults: { _controller: ArticleBundle:Article:articleCreate }

conseil_view:
    path:     /user/conseil
    defaults: { _controller: AppBundle:Conseil:conseilView }
new_photo:
    path:     /user/newphoto
    defaults: { _controller: ArticleBundle:Article:newphoto }