article:
    resource: "@ArticleBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

accueil:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

article:
    path:     /articles
    defaults: { _controller: ArticleBundle:Default:index}
article_show:
    path:     /articles
    defaults: { _controller: ArticleBundle:Article:articleShow }

article_create:
    path:     /article/new
    defaults: { _controller: ArticleBundle:Article:articleCreate }