newpoint_view:
    path:     /user/point
    defaults: { _controller: MapBundle:Point:createPointView }

create_point:
    path:     /user/newpoint
    defaults: { _controller: MapBundle:Point:newPoint }

location:
    path:    /user/location
    defaults: { _controller: MapBundle:Point:newLocation }